apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-controller
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "512Mi"
          cpu: .5
        limits:
          memory: "1Gi"
          cpu: 1
  tolerations:
    - key: "app"
      operator: "equal"
      value: " blue"
      effect: " NoSchedule"
  nodeName: node01
  nodeSelector:
    size: Large
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: Exists
